name: Checks
on: ["pull_request"]

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 10, 8]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: Run testing
        run: |
          yarn install
          npm test
      - name: Publish coverage
        run: npm run coverage
