name: Checks
on: ["pull_request"]

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [10, 12, 14, 16, 18, 19, 20]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: Run testing
        run: |
          yarn install
          npm test
  code-coverage:
    name: Code coverage
    needs: testing
    runs-on: ubuntu-18.04
    env:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Publish coverage
        run: |
          yarn install
          npm run coverage
          npm run codecov
